[package]
name = "arctis_controller"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip="symbols"

[workspace]
members = [
    ".",
    "./lib/glutin-tao",
    "./lib/egui-tao"
]

[[bin]]
name="audio"
path="src/audio.rs"

[dependencies]
anyhow = {version = "1.0", features=["backtrace"]}
log = "0.4"
env_logger = "0.10"
hidapi = "2.1"
notifica = "3.0"

egui = "0.21"
glutin = "0.30"
glow = "0.12"
egui_glow = { version = "0.21" }
raw-window-handle = "0.5"
tao = { version = "0.18.0", features = ["tray"] }
glutin-tao = {path = "./lib/glutin-tao"}
egui-tao = {path = "./lib/egui-tao"}

[target."cfg(target_os = \"windows\")".dependencies]
com-policy-config = "0.1"

[target."cfg(target_os = \"windows\")".dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Com_StructuredStorage",
    "Win32_Devices_FunctionDiscovery",
    "Devices_Custom"
]