[package]
name = "arctis_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1.0", features=["backtrace"]}
log = "0.4"
env_logger = "0.10"
hidapi = "2.1"