[package]
name = "arctis_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="audio"
path="src/audio.rs"

[[bin]]
name="gui"
path="src/gui.rs"

[dependencies]
anyhow = {version = "1.0", features=["backtrace"]}
log = "0.4"
env_logger = "0.10"
hidapi = "2.1"
com-policy-config = "0.1"

egui = "0.21.0"
glutin = "0.30.5"
glow = "0.12.0"
egui-winit = "0.21.0"
egui_glow = { version = "0.21.0", features=["winit"] }
glutin-winit = "0.3.0"
raw-window-handle = "0.5.0"


[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Com_StructuredStorage",
    "Win32_Devices_FunctionDiscovery",
    "Devices_Custom"
]