[package]
name = "headset-controller"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip="symbols"
codegen-units=1

[workspace]
members = [
    ".",
    "./lib/glutin-tao",
    "./lib/egui-tao"
]

[dependencies]
anyhow = {version = "1.0", features=["backtrace"]}
log = "0.4"
env_logger = "0.10"
hidapi = "2.1"
directories-next = "2.0"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
once_cell = "1.17"
fixed-map = "0.8"

egui = "0.21"
glutin = "0.30"
glow = "0.12"
egui_glow = { version = "0.21" }
raw-window-handle = "0.5"
tao = { version = "0.18.0", features = ["tray"] }
glutin-tao = {path = "./lib/glutin-tao"}
egui-tao = {path = "./lib/egui-tao"}

[target."cfg(not(target_os = \"windows\"))".dependencies]
notify-rust = "4.7"
png = "0.17"

[target."cfg(target_os = \"windows\")".dependencies]
com-policy-config = "0.2"
widestring = "1.0"

[target."cfg(target_os = \"windows\")".dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_Security",
    "Win32_System_Com_StructuredStorage",
    "Win32_Devices_FunctionDiscovery",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
    "Foundation_Collections",
    "Data_Xml_Dom",
    "UI_Notifications"
]

[target."cfg(target_os = \"windows\")".build-dependencies]
tauri-winres = "0.1"
ico = "0.3"